-- Flyway V1 — baseline schema for BudgetSpace AI (Sprint 10.83).
--
-- This is the authoritative production schema: it was generated from the live Hibernate-built dev database
-- (pg_dump --schema-only --no-owner --no-privileges) so a fresh prod boot creates EXACTLY what the JPA entities
-- expect, and `spring.jpa.hibernate.ddl-auto=validate` passes. From here on, EVERY schema change ships as a new
-- versioned migration (V2__*.sql, V3__*.sql, …) — never via ddl-auto in prod.
--
-- No foreign keys: ownership is by string keys (owner/session ids), matching the entities. Product rows are NOT
-- seeded here — RealCatalogSeeder repopulates the catalog at startup (idempotent upserts).

CREATE TABLE public.app_users (
    created_at timestamp(6) with time zone NOT NULL,
    last_login_at timestamp(6) with time zone NOT NULL,
    plan character varying(16) NOT NULL,
    google_sub character varying(64) NOT NULL,
    stripe_customer_id character varying(80),
    stripe_subscription_id character varying(80),
    name character varying(200),
    email character varying(320),
    picture_url character varying(1024),
    id character varying(255) NOT NULL
);

CREATE TABLE public.auth_sessions (
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    last_seen_at timestamp(6) with time zone NOT NULL,
    token character varying(64) NOT NULL,
    user_id character varying(255) NOT NULL
);

CREATE TABLE public.collector_run_items (
    data_quality character varying(40),
    status character varying(40),
    run_id character varying(80),
    external_id character varying(200),
    name character varying(300),
    url character varying(700),
    id character varying(255) NOT NULL,
    message text,
    missing_fields text,
    warnings text
);

CREATE TABLE public.collector_runs (
    fetched integer NOT NULL,
    imported integer NOT NULL,
    needs_review integer NOT NULL,
    parsed integer NOT NULL,
    skipped integer NOT NULL,
    total_received integer NOT NULL,
    updated integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    finished_at character varying(40),
    started_at character varying(40),
    retailer character varying(80),
    id character varying(255) NOT NULL,
    request_summary text
);

CREATE TABLE public.plan_feedback (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    note character varying(700),
    feedback character varying(255) NOT NULL,
    plan_id character varying(255) NOT NULL
);

ALTER TABLE public.plan_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.plus_interest (
    created_at timestamp(6) with time zone NOT NULL,
    source character varying(40),
    session_id character varying(80),
    email character varying(320),
    id character varying(255) NOT NULL
);

CREATE TABLE public.price_watches (
    active boolean DEFAULT true NOT NULL,
    baseline_price numeric(10,2) NOT NULL,
    last_notified_price numeric(10,2),
    threshold_percent integer NOT NULL,
    market character varying(8),
    consent_at character varying(40),
    created_at character varying(40),
    last_notified_at character varying(40),
    unsubscribe_token character varying(64) NOT NULL,
    retailer character varying(80),
    session_id character varying(80),
    external_id character varying(120) NOT NULL,
    email character varying(200) NOT NULL,
    product_name character varying(300),
    product_url character varying(700),
    id character varying(255) NOT NULL
);

CREATE TABLE public.product_clicks (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    plan_id character varying(255),
    product_id character varying(255) NOT NULL,
    retailer character varying(255) NOT NULL,
    source character varying(255) NOT NULL
);

ALTER TABLE public.product_clicks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_clicks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    image_verified boolean DEFAULT false NOT NULL,
    in_stock boolean NOT NULL,
    is_sponsored boolean DEFAULT false NOT NULL,
    original_price numeric(10,2),
    price numeric(10,2) NOT NULL,
    rating double precision NOT NULL,
    review_count integer,
    review_rating double precision,
    second_hand boolean DEFAULT false NOT NULL,
    market character varying(8),
    condition_label character varying(40),
    data_quality character varying(40),
    imported_at character varying(40),
    last_checked_at character varying(40),
    price_tier character varying(40),
    sale_ends_at character varying(40),
    source_type character varying(40),
    availability_status character varying(80),
    source_name character varying(80),
    external_id character varying(120),
    seller_location character varying(120),
    sponsor_label character varying(120),
    color_tags character varying(200),
    material_tags character varying(200),
    delivery_note character varying(300),
    source_reference character varying(300),
    data_quality_notes character varying(500),
    affiliate_url character varying(700),
    image character varying(700) NOT NULL,
    image_url character varying(700),
    note character varying(700) NOT NULL,
    original_product_url character varying(700),
    product_url character varying(700),
    reviews_url character varying(700),
    url character varying(700) NOT NULL,
    category character varying(255) NOT NULL,
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    retailer character varying(255) NOT NULL,
    room_tags character varying(255) NOT NULL,
    style_tags character varying(255) NOT NULL
);

CREATE TABLE public.saved_plans (
    favorite boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    session_id character varying(80),
    space_name character varying(80),
    id character varying(255) NOT NULL,
    input_json text NOT NULL,
    plan_json text NOT NULL
);

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_google_sub_key UNIQUE (google_sub);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (token);

ALTER TABLE ONLY public.collector_run_items
    ADD CONSTRAINT collector_run_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.collector_runs
    ADD CONSTRAINT collector_runs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.plan_feedback
    ADD CONSTRAINT plan_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.plus_interest
    ADD CONSTRAINT plus_interest_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.price_watches
    ADD CONSTRAINT price_watches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_clicks
    ADD CONSTRAINT product_clicks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.saved_plans
    ADD CONSTRAINT saved_plans_pkey PRIMARY KEY (id);
