-- Flyway V3 (Sprint 10.86) — durable AI usage ledger.
-- One row per REAL (non-fallback) AI call. The in-memory AiUsageTracker write-throughs here and rehydrates from
-- here on startup, so the monthly-USD wallet cap + per-user daily caps survive restarts instead of resetting to
-- zero. Matches the AiUsageRecord entity. Only metadata — no prompt text or API key.

CREATE TABLE public.ai_usage_events (
    id bigint NOT NULL,
    owner_key character varying(120),
    tier character varying(16),
    provider character varying(40),
    model character varying(80),
    use_case character varying(40),
    input_tokens integer,
    output_tokens integer,
    estimated_cost_usd double precision NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.ai_usage_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_usage_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ai_usage_events
    ADD CONSTRAINT ai_usage_events_pkey PRIMARY KEY (id);

-- Supports the rehydrate (created_at >= month-start) and the cleanup (created_at < cutoff) queries.
CREATE INDEX idx_ai_usage_events_created_at ON public.ai_usage_events (created_at);
