package ai.budgetspace.planner;

import ai.budgetspace.dto.DesignAssistantResponse;
import ai.budgetspace.dto.FurnishingPlanDto;
import ai.budgetspace.dto.PlanGenerationResponse;
import ai.budgetspace.dto.PlannerInputDto;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Sprint 10.8 — LLM-powered design assistant.
 *
 * <p>Turns an already-generated plan into a short, human-friendly description (room, budget,
 * included categories, style and store mix).</p>
 *
 * <p>Two modes, chosen at runtime:</p>
 * <ul>
 *   <li><b>Rule-based (default)</b> — deterministic Croatian text built from the plan. No external
 *       call, no latency, no cost. Always used when the LLM is disabled, no API key is configured,
 *       or the LLM call fails for any reason.</li>
 *   <li><b>LLM</b> — when {@code budgetspace.design-assistant.llm-enabled=true} and an Anthropic API
 *       key is present, the summary paragraph is generated by Claude ({@code claude-opus-4-8} by
 *       default) via the Messages API. The deterministic highlights are kept (they are verified
 *       facts, not model output), and any failure falls back to the rule-based summary.</li>
 * </ul>
 *
 * <p>The call uses the JDK HTTP client against the real Anthropic Messages API rather than the
 * {@code com.anthropic} SDK on purpose: this feature is off by default, so it must not add a build
 * dependency that could fail to resolve. For a full rollout, switching to the official Anthropic
 * Java SDK is the recommended path.</p>
 */
@Service
public class DesignAssistantService {
    private static final Logger log = LoggerFactory.getLogger(DesignAssistantService.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    // Anthropic Messages API constants (see claude-api reference).
    private static final String ANTHROPIC_VERSION = "2023-06-01";
    private static final String LLM_SYSTEM_PROMPT =
            "Ti si dizajn asistent za BudgetSpace AI. Na temelju plana opremanja napiši kratak, "
                    + "prijateljski opis na hrvatskom (2-4 rečenice): koja je soba, budžet, ključni komadi i stil. "
                    + "Odgovori isključivo tekstom opisa, bez uvoda, bez popisa i bez markdown oznaka.";

    // Config (field injection so the no-arg constructor used by tests keeps the LLM disabled).
    @Value("${budgetspace.design-assistant.llm-enabled:false}")
    private boolean llmEnabled;
    @Value("${budgetspace.design-assistant.api-key:${ANTHROPIC_API_KEY:}}")
    private String apiKey;
    @Value("${budgetspace.design-assistant.model:claude-opus-4-8}")
    private String model;
    @Value("${budgetspace.design-assistant.base-url:https://api.anthropic.com}")
    private String baseUrl;

    private static final Map<String, String> ROOM_LABELS = Map.ofEntries(
            Map.entry("living-room", "dnevni boravak"),
            Map.entry("home-office", "radni kutak"),
            Map.entry("bedroom", "spavaća soba"),
            Map.entry("home-gym", "kućna teretana"),
            Map.entry("kitchen", "kuhinja"),
            Map.entry("dining-room", "blagovaonica"),
            Map.entry("hallway", "hodnik"),
            Map.entry("bathroom", "kupaonica")
    );

    private static final Map<String, String> STYLE_LABELS = Map.ofEntries(
            Map.entry("bright", "svijetao i prozračan"),
            Map.entry("warm", "topao i ugodan"),
            Map.entry("cozy", "topao i ugodan"),
            Map.entry("modern", "moderan"),
            Map.entry("minimal", "minimalan"),
            Map.entry("scandinavian", "skandinavski"),
            Map.entry("classic", "klasičan"),
            Map.entry("industrial", "industrijski"),
            Map.entry("boho", "boho"),
            Map.entry("surprise", "prepušten našem prijedlogu")
    );

    private static final Map<String, String> COLOR_LABELS = Map.ofEntries(
            Map.entry("white", "bijela"),
            Map.entry("black", "crna"),
            Map.entry("grey", "siva"),
            Map.entry("beige", "bež"),
            Map.entry("brown", "smeđa"),
            Map.entry("green", "zelena"),
            Map.entry("blue", "plava"),
            Map.entry("yellow", "žuta"),
            Map.entry("red", "crvena"),
            Map.entry("pink", "roza"),
            Map.entry("natural", "prirodna"),
            Map.entry("gold", "zlatna")
    );

    private static final Map<String, String> MATERIAL_LABELS = Map.ofEntries(
            Map.entry("wood", "drvo"),
            Map.entry("metal", "metal"),
            Map.entry("glass", "staklo"),
            Map.entry("fabric", "tekstil"),
            Map.entry("leather", "koža"),
            Map.entry("rattan", "ratan"),
            Map.entry("marble", "mramor"),
            Map.entry("velvet", "baršun")
    );

    public DesignAssistantResponse describe(PlanGenerationResponse plan) {
        DesignAssistantResponse ruleBased = ruleBasedDescribe(plan);
        if (!llmEnabled || !hasText(apiKey) || plan == null || plan.input() == null) {
            return ruleBased;
        }
        FurnishingPlanDto primary = primaryPlan(plan.plans());
        if (primary == null || primary.items().isEmpty()) {
            return ruleBased; // nothing concrete to describe — keep the deterministic message
        }
        try {
            return llmDescribe(plan, primary, ruleBased);
        } catch (Exception exception) {
            log.warn("Design assistant LLM call failed ({}); using rule-based fallback.", exception.toString());
            return ruleBased;
        }
    }

    // Calls the Anthropic Messages API for the summary paragraph; keeps the deterministic highlights.
    private DesignAssistantResponse llmDescribe(PlanGenerationResponse plan, FurnishingPlanDto primary,
                                                DesignAssistantResponse ruleBased) throws IOException, InterruptedException {
        String userPrompt = buildLlmPrompt(plan.input(), primary);
        Map<String, Object> body = Map.of(
                "model", model,
                "max_tokens", 600,
                "system", LLM_SYSTEM_PROMPT,
                "messages", List.of(Map.of("role", "user", "content", userPrompt)));

        HttpRequest request = HttpRequest.newBuilder(URI.create(baseUrl + "/v1/messages"))
                .header("x-api-key", apiKey)
                .header("anthropic-version", ANTHROPIC_VERSION)
                .header("content-type", "application/json")
                .timeout(Duration.ofSeconds(20))
                .POST(HttpRequest.BodyPublishers.ofString(MAPPER.writeValueAsString(body), StandardCharsets.UTF_8))
                .build();

        HttpResponse<String> response = HttpClient.newHttpClient()
                .send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
        if (response.statusCode() != 200) {
            throw new IOException("Anthropic API returned status " + response.statusCode());
        }

        JsonNode root = MAPPER.readTree(response.body());
        // Always check stop_reason before reading content — a refusal carries empty/partial content.
        if ("refusal".equals(root.path("stop_reason").asText(""))) {
            throw new IOException("model refused the request");
        }
        StringBuilder summary = new StringBuilder();
        for (JsonNode block : root.path("content")) {
            if ("text".equals(block.path("type").asText())) {
                summary.append(block.path("text").asText());
            }
        }
        String text = summary.toString().trim();
        if (text.isEmpty()) {
            throw new IOException("empty model response");
        }
        logSummary(plan.input(), primary, primary.items().size());
        return new DesignAssistantResponse(text, ruleBased.highlights());
    }

    private String buildLlmPrompt(PlannerInputDto input, FurnishingPlanDto primary) {
        String room = ROOM_LABELS.getOrDefault(input.roomType(), input.roomType());
        String style = STYLE_LABELS.getOrDefault(input.style(), input.style());
        String items = primary.items().stream()
                .map(item -> "- " + item.product().name() + " (" + categoryLabel(item.product().category())
                        + ", " + money(item.product().price()) + " €, " + item.product().retailer() + ")")
                .reduce((a, b) -> a + "\n" + b)
                .orElse("(nema stavki)");
        String prefs = preferenceLabels(input);
        return "Soba: " + room + "\n"
                + "Budžet: do " + money(input.budget()) + " €\n"
                + "Stil: " + style + "\n"
                + (prefs == null ? "" : "Tražene boje/materijali: " + prefs + "\n")
                + "Ukupno: " + money(primary.total()) + " € (" + budgetFitClause(input, primary) + ")\n"
                + "Proizvodi:\n" + items;
    }

    private DesignAssistantResponse ruleBasedDescribe(PlanGenerationResponse plan) {
        if (plan == null || plan.input() == null) {
            return new DesignAssistantResponse(
                    "Još nemam dovoljno podataka za opis plana. Prvo složi plan, pa ću ga ovdje ukratko opisati.",
                    List.of());
        }

        PlannerInputDto input = plan.input();
        FurnishingPlanDto primary = primaryPlan(plan.plans());
        String room = ROOM_LABELS.getOrDefault(input.roomType(), input.roomType());
        String budget = money(input.budget());

        if (primary == null || primary.items().isEmpty()) {
            String summary = "Za " + room + " s budžetom do " + budget
                    + " € još nemamo dovoljno proizvoda u katalogu za konkretan prijedlog. "
                    + "Pokušaj povećati budžet ili ukloniti ograničenje trgovine.";
            logSummary(input, primary, 0);
            return new DesignAssistantResponse(summary, List.of());
        }

        List<String> categories = primary.items().stream()
                .map(item -> categoryLabel(item.product().category()))
                .distinct()
                .toList();
        String categoryList = joinHuman(categories);
        String style = STYLE_LABELS.getOrDefault(input.style(), input.style());

        StringBuilder summary = new StringBuilder()
                .append("Za ").append(room)
                .append(" s budžetom do ").append(budget).append(" € složili smo plan „")
                .append(primary.name()).append("” s ").append(primary.items().size())
                .append(" ").append(productsWord(primary.items().size())).append(" (").append(categoryList).append(").")
                .append(" Stil je ").append(style).append(prefClause(input)).append(".")
                .append(" ").append(storeClause(primary)).append(" Ukupna procjena je ")
                .append(money(primary.total())).append(" € (").append(budgetFitClause(input, primary)).append(").");

        List<String> highlights = buildHighlights(input, primary, plan);
        logSummary(input, primary, primary.items().size());
        return new DesignAssistantResponse(summary.toString(), highlights);
    }

    private List<String> buildHighlights(PlannerInputDto input, FurnishingPlanDto primary, PlanGenerationResponse plan) {
        List<String> highlights = new ArrayList<>();
        String coreItems = primary.items().stream()
                .filter(item -> "buy-first".equals(item.shoppingPriority()))
                .map(item -> item.product().name())
                .limit(3)
                .reduce((a, b) -> a + ", " + b)
                .orElse("");
        if (!coreItems.isBlank()) {
            highlights.add("Glavni komadi: " + coreItems + ".");
        }
        highlights.add("Ukupno " + money(primary.total()) + " € · " + budgetFitClause(input, primary) + ".");
        if (primary.retailersUsed() != null && !primary.retailersUsed().isEmpty()) {
            highlights.add("Trgovine: " + String.join(" + ", primary.retailersUsed()) + ".");
        }
        String prefs = preferenceHighlight(input);
        if (prefs != null) highlights.add(prefs);
        if (plan.partialPlan() && plan.catalogWarning() != null) {
            highlights.add(plan.catalogWarning());
        }
        return highlights;
    }

    private FurnishingPlanDto primaryPlan(List<FurnishingPlanDto> plans) {
        if (plans == null || plans.isEmpty()) return null;
        return plans.stream()
                .filter(plan -> "Najbolji izbor".equals(plan.name()) || "value".equals(plan.id()))
                .findFirst()
                .orElse(plans.get(0));
    }

    private String prefClause(PlannerInputDto input) {
        String labels = preferenceLabels(input);
        return labels == null ? "" : ", a tražene boje/materijali su " + labels;
    }

    private String preferenceHighlight(PlannerInputDto input) {
        String labels = preferenceLabels(input);
        return labels == null ? null : "Boje/materijali koje si tražio: " + labels + ".";
    }

    private String preferenceLabels(PlannerInputDto input) {
        List<String> labels = new ArrayList<>();
        if (input.colorPreferences() != null) {
            input.colorPreferences().forEach(color -> labels.add(COLOR_LABELS.getOrDefault(color, color)));
        }
        if (input.materialPreferences() != null) {
            input.materialPreferences().forEach(material -> labels.add(MATERIAL_LABELS.getOrDefault(material, material)));
        }
        return labels.isEmpty() ? null : joinHuman(labels);
    }

    private String storeClause(FurnishingPlanDto primary) {
        List<String> retailers = primary.retailersUsed();
        if (retailers == null || retailers.isEmpty()) return "Kupnja je iz jedne trgovine.";
        if (retailers.size() == 1) return "Sve kupuješ u " + retailers.get(0) + ".";
        return "Kupnja kombinira " + String.join(" i ", retailers) + ".";
    }

    private String budgetFitClause(PlannerInputDto input, FurnishingPlanDto primary) {
        return primary.total().doubleValue() <= input.budget() ? "unutar budžeta" : "malo iznad budžeta";
    }

    private String categoryLabel(String category) {
        return PlannerReadiness.categoryLabel(category);
    }

    private String joinHuman(List<String> values) {
        if (values == null || values.isEmpty()) return "";
        if (values.size() == 1) return values.get(0);
        return String.join(", ", values.subList(0, values.size() - 1)) + " i " + values.get(values.size() - 1);
    }

    private String productsWord(int count) {
        int mod10 = count % 10;
        int mod100 = count % 100;
        if (mod10 == 1 && mod100 != 11) return "proizvodom";
        if (mod10 >= 2 && mod10 <= 4 && !(mod100 >= 12 && mod100 <= 14)) return "proizvoda";
        return "proizvoda";
    }

    private String money(double value) {
        return BigDecimal.valueOf(value).stripTrailingZeros().toPlainString();
    }

    private String money(BigDecimal value) {
        return value == null ? "0" : value.stripTrailingZeros().toPlainString();
    }

    private boolean hasText(String value) {
        return value != null && !value.isBlank();
    }

    private void logSummary(PlannerInputDto input, FurnishingPlanDto primary, int itemCount) {
        String total = primary == null ? "0" : money(primary.total());
        log.info("Design assistant: room={}, budget={} EUR, items={}, total={} EUR (rule-based stub).",
                input.roomType(), input.budget(), itemCount, total);
    }
}
